# Site settings
title: LosFuzzys
email: crypto+losfuzzyswebsite@2904.cc
description: "LosFuzzys ist a CTF team located in Graz, Europe."
baseurl: ""
url: "https://losfuzzys.github.io"
twitter_username: losfuzzys
github_username:  losfuzzys

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
    input: GFM

# github gems
# (see https://help.github.com/categories/github-pages-features/ )
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
#  - jekyll-mentions

authors:
  verr:
    display_name: verr
    web: https://twitter.com/stefan2904
  f0rki:
    display_name: f0rki
    web: https://twitter.com/f0rki
  kw:
    web: https://twitter.com/__kaydoubleu__
  skogler:
    display_name: skogler
  creed:
  kree:
  sigttou:
    web: https://twitter.com/sigttou
  roman:
